#ifndef _DRA7XX_CPU_H
#define _DRA7XX_CPU_H

#define CLKCTRL_MODULEMODE_OFFSET               0
#define CLKCTRL_MODULEMODE_WIDTH                2
#define CLKCTRL_MODULEMODE_MASK                 (0x3 << CLKCTRL_MODULEMODE_OFFSET)
#define CLKCTRL_MODULEMODE_DISABLED             (0 << CLKCTRL_MODULEMODE_OFFSET)
#define CLKCTRL_MODULEMODE_AUTO                 (1 << CLKCTRL_MODULEMODE_OFFSET)
#define CLKCTRL_MODULEMODE_ENABLED              (2 << CLKCTRL_MODULEMODE_OFFSET)

#define CLKCTRL_OPTCLKEN_OFFSET                 8
#define CLKCTRL_OPTCLKEN_DISABLED               (0 << CLKCTRL_OPTCLKEN_OFFSET)
#define CLKCTRL_OPTCLKEN_ENABLED                (1 << CLKCTRL_OPTCLKEN_OFFSET)

#define CLKCTRL_IDLEST_OFFSET                   16
#define CLKCTRL_IDLEST_MASK                     (0x3 << CLKCTRL_IDLEST_OFFSET)
#define CLKCTRL_IDLEST_FUNCTIONAL               (0x0 << CLKCTRL_IDLEST_OFFSET)
#define CLKCTRL_IDLEST_TRANSITION               (0x1 << CLKCTRL_IDLEST_OFFSET)
#define CLKCTRL_IDLEST_IDLE                     (0x2 << CLKCTRL_IDLEST_OFFSET)
#define CLKCTRL_IDLEST_DISABLED                 (0x3 << CLKCTRL_IDLEST_OFFSET)

#define CLKCTRL_CLKSEL_OFFSET                   24
#define CLKCTRL_CLKSEL_MSK                      (1 << CLKCTRL_CLKSEL_OFFSET)
#define CLKCTRL_CLKSEL_DIV_OFF                  25
#define CLKCTRL_CLKSEL_DIV_MSK                  (3 << CLKCTRL_CLKSEL_DIV_OFF)

/* These are common definitions for those _CLKSTCTRL registers */
#define CLKSTCTRL_CLKTRCTRL_OFFSET              0
#define CLKSTCTRL_CLKTRCTRL_WIDTH               2
#define CLKSTCTRL_CLKTRCTRL_MASK                (0x3 << CLKSTCTRL_CLKTRCTRL_OFFSET)
#define CLKSTCTRL_CLKTRCTRL_NO_SLEEP            (0x0 << CLKSTCTRL_CLKTRCTRL_OFFSET)
#define CLKSTCTRL_CLKTRCTRL_SW_SEEP             (0x1 << CLKSTCTRL_CLKTRCTRL_OFFSET)
#define CLKSTCTRL_CLKTRCTRL_SW_WKUP             (0x2 << CLKSTCTRL_CLKTRCTRL_OFFSET)
#define CLKSTCTRL_CLKTRCTRL_HW_AUTO             (0x3 << CLKSTCTRL_CLKTRCTRL_OFFSET)

#define CLKSTCTRL_CLKACTIVITY_OFFSET            8
#define CLKSTCTRL_CLKACTIVITY_MASK              (1 << CLKSTCTRL_CLKACTIVITY_OFFSET)
#define CLKSTCTRL_CLKACTIVITY_GATED             (0 << CLKSTCTRL_CLKACTIVITY_OFFSET)
#define CLKSTCTRL_CLKACTIVITY_RUNNING           (1 << CLKSTCTRL_CLKACTIVITY_OFFSET)



#endif

